<?php
/**
 * @category    design
 * @package     default_default
 */
?>

<?php if ($this->getGcontentCaptchaToken() && $this->getGcontentCaptchaUrl()): ?>
<ul class="messages">
    <li class="error-msg">
        <ul>
            <li><img src="<?php echo $this->getGcontentCaptchaUrl() ?>"> <input type="text" id="user_confirm"> <?php echo $this->getConfirmButtonHtml() ?></li>
        </ul>
    </li>
</ul>
<?php endif; ?>
