<?php
/**
 * Use this template to display the sidebar menu inside static blocks and pages.
 */
?>
<?php
    $helper = Mage::helper('ultramegamenu');
    $visibilityClass = $helper->getCfg('sidemenu/hide_on_mobile') ? ' hide-below-768' : '';

    //Get starting category - a point where traverse begins
    $categoryId = $this->getParent();
    if ($categoryId === NULL) //Param not set
    {
        $categoryId = $helper->getCfg('sidemenu/parent');
    }

    //Get depth of recursion - how many levels of subcategories retrieve
//    $depth = $this->getDepth();
    $depth = 5;
    
    if ($depth === NULL) //Param not set
    {
        $depth = intval($helper->getCfg('sidemenu/depth'));
    }
    else
    {
        $depth = intval($depth);
    }
    $currentCat = Mage::registry('current_category');
   
    while($currentCat->getParentId() != Mage::app()->getStore()->getRootCategoryId())
    {
        $currentCat = Mage::getModel('catalog/category')->load($currentCat->getParentId());
    }
    $categoryId = $currentCat->getId();
    //Render categories menu HTML
//    $html = $this->renderMe(TRUE);
    $html = $this->renderMe(TRUE, $categoryId, $depth); 
	if (!$html)
    {
        return '';
    }
	
?>
<div class="block block-vertnav<?php echo $visibilityClass; ?>">
    <div class="block-title">
        <strong><span><?php echo $this->renderBlockTitle(); ?></span></strong>
    </div>
    <div class="block-content">
	
        <ul class="accordion accordion-style1 vertnav vertnav-side clearer"> <?php //Class "vertnav-side" left for backward compatibility ?>
            <?php echo $html; ?>
        </ul>
    </div>
</div>
<!--<a class="button" href="<?php // echo Mage::getBaseUrl().'brand-directory';?>">Shop by Brand</a>-->
<script>
    if(location.pathname == "/headphones.html" 
            || location.pathname == "/headphones/in-ear-monitors.html"
            || location.pathname == "/headphones/earphone-earbud-cable.html"){
jQuery(document).on('click','.opener',function(){
   var hrefurl = jQuery(this).parent().find('a').attr('href');
   if(hrefurl.search('type.html') >= 0 || hrefurl.search('by-brand.html') >= 0){
       if(jQuery(this).parent().find('ul').css('display') == 'none'){
            jQuery(this).parent().parent().find('.parent ul').hide();
            jQuery(this).parent().find('ul').show();
            jQuery(this).parent().addClass('item-active');
       } else {
            jQuery(this).parent().find('ul').hide();
            jQuery(this).parent().removeClass('item-active');
       }
   }
});
            }
</script>

